profile=high-quality
vo=gpu-next
scale-antiring=0.6

dither-depth = 8

image-display-duration=inf
save-position-on-quit
keep-open=yes

screenshot-format=png
screenshot-high-bit-depth=no

slang=eng,en
alang=jpn,ja
